// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package llm

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockILLM creates a new instance of MockILLM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILLM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILLM {
	mock := &MockILLM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILLM is an autogenerated mock type for the ILLM type
type MockILLM struct {
	mock.Mock
}

type MockILLM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILLM) EXPECT() *MockILLM_Expecter {
	return &MockILLM_Expecter{mock: &_m.Mock}
}

// GetEmbedding provides a mock function for the type MockILLM
func (_mock *MockILLM) GetEmbedding(text string, dim int) ([]float32, error) {
	ret := _mock.Called(text, dim)

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedding")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]float32, error)); ok {
		return returnFunc(text, dim)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []float32); ok {
		r0 = returnFunc(text, dim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(text, dim)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILLM_GetEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbedding'
type MockILLM_GetEmbedding_Call struct {
	*mock.Call
}

// GetEmbedding is a helper method to define mock.On call
//   - text string
//   - dim int
func (_e *MockILLM_Expecter) GetEmbedding(text any, dim any) *MockILLM_GetEmbedding_Call {
	return &MockILLM_GetEmbedding_Call{Call: _e.mock.On("GetEmbedding", text, dim)}
}

func (_c *MockILLM_GetEmbedding_Call) Run(run func(text string, dim int)) *MockILLM_GetEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILLM_GetEmbedding_Call) Return(float32s []float32, err error) *MockILLM_GetEmbedding_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockILLM_GetEmbedding_Call) RunAndReturn(run func(text string, dim int) ([]float32, error)) *MockILLM_GetEmbedding_Call {
	_c.Call.Return(run)
	return _c
}
